license = "BSD3"
with_readme = true

[files]
directories = ["src", "app", "ats-src", "cbits", "test", "bench"]
templates = [ "src/Lib.hs"
            , "{{ project }}.cabal"
            , "Setup.hs"
            , "app/Main.hs"
            , "cabal.project.local"
            , "test/Spec.hs"
            , "ats-src/{{ project }}.dats"
            , "bench/Bench.hs"
            , "Setup.hs"
            , ".travis.yml"
            , ".stylish-haskell.yaml"
            , ".hlint.yaml"
            , ".yamllint"
            ]
scripts = [ "shake.hs" ]

[config]
version = "0.1.0.0"
version_control = "git"
